name: cineflix
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.0
  http: ^0.13.5
  shared_preferences: ^2.1.0
  share_plus: ^6.3.2
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_native_splash: ^2.2.19
  json_serializable: ^6.6.1

flutter_native_splash:
  image: assets/splashscreen/splashscreen.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/cineflix.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
  
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300


